name: tests

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "tests/**"
      - "vcpkg.json"
      - "CMakeLists.txt"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  BUILD_TYPE: "Release"
  VCPKG_VERSION: "83972272512ce4ede5fc3b2ba98f6468b179f192"

jobs:
  build-and-test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            generator: 'Ninja'
          - os: ubuntu-latest
            generator: 'Unix Makefiles'
          - os: macos-latest
            generator: 'Unix Makefiles'

    steps:
      - uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
          vcpkgGitCommitId: '${{ env.VCPKG_VERSION }}'

      - name: Run CMake
        run: cmake -B build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_TOOLCHAIN_FILE=${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build -V
