name: clang-format

on:
  push:
    branches: [ "main" ]
    paths: 
      - "src/**"
      - "misc/format.sh"
      - ".clang-format"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  clang-format-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Run clang-format
      run: |
        ./misc/format.sh
        git diff --exit-code
